/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R69EasyRouteImport } from './routes/69-easy'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WorkWithMeRouteImport } from './routes/work-with-me'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminIdeasRouteImport } from './routes/admin.ideas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PurchaseSuccessRouteImport } from './routes/purchase.success'
import { Route as ApiAdminLiveRouteImport } from './routes/api/admin/live'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCoachingCheckoutRouteImport } from './routes/api/coaching/checkout'
import { Route as ApiCoachingPortalRouteImport } from './routes/api/coaching/portal'
import { Route as ApiProgramDownloadRouteImport } from './routes/api/program/download'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R69EasyRoute = R69EasyRouteImport.update({
  id: '/69-easy',
  path: '/69-easy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWithMeRoute = WorkWithMeRouteImport.update({
  id: '/work-with-me',
  path: '/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdeasRoute = AdminIdeasRouteImport.update({
  id: '/admin/ideas',
  path: '/admin/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const PurchaseSuccessRoute = PurchaseSuccessRouteImport.update({
  id: '/purchase/success',
  path: '/purchase/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLiveRoute = ApiAdminLiveRouteImport.update({
  id: '/api/admin/live',
  path: '/api/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachingCheckoutRoute = ApiCoachingCheckoutRouteImport.update({
  id: '/api/coaching/checkout',
  path: '/api/coaching/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachingPortalRoute = ApiCoachingPortalRouteImport.update({
  id: '/api/coaching/portal',
  path: '/api/coaching/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgramDownloadRoute = ApiProgramDownloadRouteImport.update({
  id: '/api/program/download',
  path: '/api/program/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/69-easy': typeof R69EasyRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/signup': typeof SignupRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/api/admin/live': typeof ApiAdminLiveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coaching/checkout': typeof ApiCoachingCheckoutRoute
  '/api/coaching/portal': typeof ApiCoachingPortalRoute
  '/api/program/download': typeof ApiProgramDownloadRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/69-easy': typeof R69EasyRoute
  '/account': typeof AccountRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/signup': typeof SignupRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/blog': typeof BlogIndexRoute
  '/api/admin/live': typeof ApiAdminLiveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coaching/checkout': typeof ApiCoachingCheckoutRoute
  '/api/coaching/portal': typeof ApiCoachingPortalRoute
  '/api/program/download': typeof ApiProgramDownloadRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/69-easy': typeof R69EasyRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/signup': typeof SignupRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/api/admin/live': typeof ApiAdminLiveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coaching/checkout': typeof ApiCoachingCheckoutRoute
  '/api/coaching/portal': typeof ApiCoachingPortalRoute
  '/api/program/download': typeof ApiProgramDownloadRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/69-easy'
    | '/account'
    | '/blog'
    | '/coach'
    | '/dashboard'
    | '/disclaimer'
    | '/login'
    | '/onboarding'
    | '/portal'
    | '/privacy'
    | '/program'
    | '/signup'
    | '/work-with-me'
    | '/admin/content'
    | '/admin/ideas'
    | '/admin/login'
    | '/api/checkout'
    | '/blog/$slug'
    | '/purchase/success'
    | '/blog/'
    | '/api/admin/live'
    | '/api/auth/$'
    | '/api/coaching/checkout'
    | '/api/coaching/portal'
    | '/api/program/download'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/69-easy'
    | '/account'
    | '/coach'
    | '/dashboard'
    | '/disclaimer'
    | '/login'
    | '/onboarding'
    | '/portal'
    | '/privacy'
    | '/program'
    | '/signup'
    | '/work-with-me'
    | '/admin/content'
    | '/admin/ideas'
    | '/admin/login'
    | '/api/checkout'
    | '/blog/$slug'
    | '/purchase/success'
    | '/blog'
    | '/api/admin/live'
    | '/api/auth/$'
    | '/api/coaching/checkout'
    | '/api/coaching/portal'
    | '/api/program/download'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/69-easy'
    | '/account'
    | '/blog'
    | '/coach'
    | '/dashboard'
    | '/disclaimer'
    | '/login'
    | '/onboarding'
    | '/portal'
    | '/privacy'
    | '/program'
    | '/signup'
    | '/work-with-me'
    | '/admin/content'
    | '/admin/ideas'
    | '/admin/login'
    | '/api/checkout'
    | '/blog/$slug'
    | '/purchase/success'
    | '/blog/'
    | '/api/admin/live'
    | '/api/auth/$'
    | '/api/coaching/checkout'
    | '/api/coaching/portal'
    | '/api/program/download'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R69EasyRoute: typeof R69EasyRoute
  AccountRoute: typeof AccountRoute
  BlogRoute: typeof BlogRouteWithChildren
  CoachRoute: typeof CoachRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramRoute: typeof ProgramRoute
  SignupRoute: typeof SignupRoute
  WorkWithMeRoute: typeof WorkWithMeRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminIdeasRoute: typeof AdminIdeasRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  PurchaseSuccessRoute: typeof PurchaseSuccessRoute
  ApiAdminLiveRoute: typeof ApiAdminLiveRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoachingCheckoutRoute: typeof ApiCoachingCheckoutRoute
  ApiCoachingPortalRoute: typeof ApiCoachingPortalRoute
  ApiProgramDownloadRoute: typeof ApiProgramDownloadRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/69-easy': {
      id: '/69-easy'
      path: '/69-easy'
      fullPath: '/69-easy'
      preLoaderRoute: typeof R69EasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-with-me': {
      id: '/work-with-me'
      path: '/work-with-me'
      fullPath: '/work-with-me'
      preLoaderRoute: typeof WorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ideas': {
      id: '/admin/ideas'
      path: '/admin/ideas'
      fullPath: '/admin/ideas'
      preLoaderRoute: typeof AdminIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/purchase/success': {
      id: '/purchase/success'
      path: '/purchase/success'
      fullPath: '/purchase/success'
      preLoaderRoute: typeof PurchaseSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/live': {
      id: '/api/admin/live'
      path: '/api/admin/live'
      fullPath: '/api/admin/live'
      preLoaderRoute: typeof ApiAdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coaching/checkout': {
      id: '/api/coaching/checkout'
      path: '/api/coaching/checkout'
      fullPath: '/api/coaching/checkout'
      preLoaderRoute: typeof ApiCoachingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coaching/portal': {
      id: '/api/coaching/portal'
      path: '/api/coaching/portal'
      fullPath: '/api/coaching/portal'
      preLoaderRoute: typeof ApiCoachingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/program/download': {
      id: '/api/program/download'
      path: '/api/program/download'
      fullPath: '/api/program/download'
      preLoaderRoute: typeof ApiProgramDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R69EasyRoute: R69EasyRoute,
  AccountRoute: AccountRoute,
  BlogRoute: BlogRouteWithChildren,
  CoachRoute: CoachRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramRoute: ProgramRoute,
  SignupRoute: SignupRoute,
  WorkWithMeRoute: WorkWithMeRoute,
  AdminContentRoute: AdminContentRoute,
  AdminIdeasRoute: AdminIdeasRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  PurchaseSuccessRoute: PurchaseSuccessRoute,
  ApiAdminLiveRoute: ApiAdminLiveRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoachingCheckoutRoute: ApiCoachingCheckoutRoute,
  ApiCoachingPortalRoute: ApiCoachingPortalRoute,
  ApiProgramDownloadRoute: ApiProgramDownloadRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
